name: kutum_cepte_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  provider: ^6.1.2
  stacked: ^3.4.3

  #UI
  kartal: ^4.1.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_screenutil: ^5.9.3

  #Json
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5

  #Network
  dio: ^5.7.0
  vexana: ^5.0.1

  #Navigation
  auto_route: ^9.2.2

  #Dependency Injection
  get_it: ^7.1.4

  #Image
  image: ^4.3.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  camera: ^0.10.5+9
  cached_network_image: ^3.4.1

  #Splash
  flutter_native_splash: ^2.3.10

  #Text
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0

  #Locale Database
  flutter_secure_storage: ^9.0.0

  #Pagination
  infinite_scroll_pagination: ^4.0.0

  #Connectivity

  #Permission
  permission_handler: ^11.3.1

  #Chart
  fl_chart: ^0.69.0

  #Google Map
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2

  #Rating
  flutter_rating_bar: ^4.0.1

  #Firebase
  firebase_core: ^3.5.0
  firebase_storage: ^12.1.1

  #HTML
  flutter_widget_from_html: ^0.15.3

  is_first_run: ^1.0.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  country_code_text_field: ^1.1.2

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
